'use client';
import {useEffect,useState} from 'react'; import {supabase} from '@/lib/supabase';
export default function MasterTeacher(){const [profile,setProfile]=useState<any>(null),[report,setReport]=useState<any>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[intervention,setIntervention]=useState<any>(null);
async function token(){const {data}=await supabase!.auth.getSession();if(!data.session){location.href='/login';return null}return data.session.access_token}
useEffect(()=>{(async()=>{const {data}=await supabase!.auth.getUser();if(data.user){const {data:p}=await supabase!.from('profiles').select('role,grade,class_name,full_name').eq('id',data.user.id).single();setProfile(p)}})()},[]);
async function analyze(){setBusy(true);setMsg('');try{const t=await token();if(!t)return;const r=await fetch('/api/ai/teacher/master',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({grade:profile?.grade,class_name:profile?.class_name})});const j=await r.json();if(!r.ok)throw Error(j.error||'Không phân tích được');setReport(j.report)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
async function makeIntervention(rec:any){setBusy(true);try{const t=await token();if(!t)return;const r=await fetch('/api/ai/teacher/master/intervention',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({class_name:report.class_name,grade:report.grade,student_ids:rec.student_ids||[],lesson_ids:rec.lesson_ids||[],recommendation:rec})});const j=await r.json();if(!r.ok)throw Error(j.error||'Không tạo được kế hoạch');setIntervention(j.intervention)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
return <main className="max-w-7xl mx-auto px-5 py-10"><div className="flex justify-between gap-4 flex-wrap"><div><div className="text-sm font-bold text-indigo-700">KHTN SỐ · V10</div><h1 className="text-4xl font-black">AI Master Teacher</h1><p className="text-slate-600 mt-2">Bảng điều khiển toàn lớp dựa trên bài làm thật và dữ liệu năng lực.</p></div><button className="btn bg-indigo-900 text-white" onClick={analyze} disabled={busy}>Phân tích lớp</button></div>{msg&&<div className="card mt-5 text-red-700">{msg}</div>}
{!report?<div className="card mt-6"><p>Giáo viên: <b>{profile?.full_name||'—'}</b> · Lớp: <b>{profile?.class_name||'—'}</b> · Khối: <b>{profile?.grade||'—'}</b></p><p className="text-slate-500 mt-2">Nhấn “Phân tích lớp” để hệ thống tổng hợp các bài đã nộp.</p></div>:<><section className="grid md:grid-cols-4 gap-4 mt-6"><div className="card"><span className="text-sm text-slate-500">Học sinh</span><div className="text-3xl font-black">{report.summary.students}</div></div><div className="card"><span className="text-sm text-slate-500">Lượt nộp</span><div className="text-3xl font-black">{report.summary.submitted_attempts}</div></div><div className="card"><span className="text-sm text-slate-500">Điểm TB</span><div className="text-3xl font-black">{report.summary.average_score??'—'}</div></div><div className="card"><span className="text-sm text-slate-500">Bài cần củng cố</span><div className="text-3xl font-black">{(report.lessons||[]).filter((x:any)=>x.mastery<80).length}</div></div></section>
<section className="card mt-5"><h2 className="text-xl font-black">Bản đồ kiến thức của lớp</h2><div className="space-y-3 mt-4">{(report.lessons||[]).map((x:any)=><div key={x.lesson_id}><div className="flex justify-between text-sm"><b>{x.lesson_title}</b><span>{x.mastery}%</span></div><div className="h-3 bg-slate-100 rounded-full overflow-hidden mt-1"><div className="h-full bg-indigo-600" style={{width:`${x.mastery}%`}}/></div></div>)}</div></section>
<section className="grid lg:grid-cols-3 gap-4 mt-5">{(report.groups||[]).map((g:any)=><div className="card" key={g.key}><h2 className="font-black text-lg">{g.title}</h2><div className="text-3xl font-black mt-2">{g.student_ids.length}</div><p className="text-sm text-slate-500">học sinh</p></div>)}</section>
<section className="card mt-5"><h2 className="text-xl font-black">Khuyến nghị can thiệp của AI</h2>{report.ai?.summary&&<p className="mt-2 text-slate-700">{report.ai.summary}</p>}<div className="space-y-3 mt-4">{(report.ai?.recommendations||[]).map((r:any,i:number)=><article className="border rounded-xl p-4" key={i}><div className="flex justify-between gap-3"><b>{r.action}</b><span className="badge">{r.priority}</span></div><p className="text-sm mt-2">{r.reason}</p><p className="text-xs text-slate-500 mt-2">{r.target} · {r.duration_minutes||0} phút · {r.student_ids?.length||0} HS</p><button className="btn border mt-3" onClick={()=>makeIntervention(r)} disabled={busy}>Tạo kế hoạch can thiệp</button></article>)}</div></section>
<section className="card mt-5"><h2 className="text-xl font-black">Danh sách học sinh cần chú ý</h2><div className="overflow-auto mt-3"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th className="py-2">Học sinh</th><th>Mã</th><th>Điểm TB</th><th>Lỗ hổng chính</th></tr></thead><tbody>{(report.students||[]).filter((s:any)=>s.needs_support).map((s:any)=><tr className="border-b" key={s.student_id}><td className="py-2 font-semibold">{s.name}</td><td>{s.student_code||'—'}</td><td>{s.average_score??'—'}</td><td>{s.weak_lessons?.map((x:any)=>x.lesson_title).join(', ')||'—'}</td></tr>)}</tbody></table></div></section>
{intervention&&<section className="card mt-5"><h2 className="text-xl font-black">{intervention.title}</h2><p className="mt-2">{intervention.plan?.objective}</p><ol className="list-decimal ml-5 mt-3 space-y-2">{(intervention.plan?.steps||[]).map((x:any,i:number)=><li key={i}><b>{x.minute} phút:</b> {x.activity} <span className="text-slate-500">({x.group})</span></li>)}</ol></section>}</>}
</main>}
