'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase';

type Tab='lesson_plan'|'question_set'|'matrix'|'exam_blueprint'|'question_review'|'activity';
const tabs:[Tab,string][]=[['lesson_plan','KHBD'],['question_set','Tạo câu hỏi'],['matrix','Ma trận'],['exam_blueprint','Cấu trúc đề'],['question_review','Kiểm định câu hỏi'],['activity','Hoạt động/STEM']];
const grades=['6','7','8','9','10','11','12'];

export default function TeacherAI(){
 const [tab,setTab]=useState<Tab>('lesson_plan'),[grade,setGrade]=useState('7'),[lessonId,setLessonId]=useState(''),[lessons,setLessons]=useState<any[]>([]),[request,setRequest]=useState(''),[count,setCount]=useState(5),[answer,setAnswer]=useState<any>(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[saved,setSaved]=useState(''),[projectId,setProjectId]=useState('');
 useEffect(()=>{supabase?.from('curriculum').select('id,grade,chapter_code,lesson_no,lesson_title').order('grade').order('sort_order').then(({data})=>setLessons(data||[]));},[]);
 const filtered=useMemo(()=>lessons.filter(x=>x.grade===grade),[lessons,grade]);
 async function session(){const {data:{session}}=await supabase!.auth.getSession();if(!session){location.href='/login';throw new Error('UNAUTHENTICATED')}return session}
 async function run(){setBusy(true);setMsg('');setSaved('');setAnswer('');try{const s=await session();let endpoint='/api/ai/teacher';let body:any={task:tab,request,grade,lesson_id:lessonId||null};if(tab==='question_set'){endpoint='/api/ai/question';body={...body,type:'mixed',count,topic:request}}if(tab==='matrix'){endpoint='/api/ai/exam/matrix';body={...body,request,total_questions:count,total_points:10}}if(tab==='exam_blueprint'){endpoint='/api/ai/exam';body={...body,request,count}}const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.access_token}`},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'AI lỗi');setAnswer(tab==='question_set'?(j.questions||[]):(j.matrix||j.answer||''));}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function saveProject(){try{const s=await session();const title=tabs.find(x=>x[0]===tab)?.[1]||'AI Teacher';const r=await fetch('/api/ai/teacher/save',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.access_token}`},body:JSON.stringify({kind:tab,title:`${title} · Lớp ${grade}`,grade,lesson_id:lessonId||null,input:{request,count},output:answer})});const j=await r.json();if(!r.ok)throw new Error(j.error);setProjectId(j.project.id);setSaved(`Đã lưu dự án ${j.project.id.slice(0,8)}…`)}catch(e:any){setMsg(e.message)}}
 async function saveQuestions(){if(!Array.isArray(answer)||!answer.length)return; if(!projectId){await saveProject();}const rows=answer.map((q:any)=>({type:q.type,prompt:q.prompt,options:q.options||null,answer:q.answer,points:Number(q.points||0.25),lesson_id:lessonId||null,status:'draft',metadata:{source:'AI Teacher V6',explanation:q.explanation||''},ai_source_project_id:projectId||null}));const {error}=await supabase!.from('question_bank').insert(rows);if(error)setMsg(error.message);else setSaved(`Đã lưu ${rows.length} câu vào ngân hàng ở trạng thái Nháp.`)}
 return <main className="max-w-7xl mx-auto px-5 py-10"><div className="flex flex-wrap justify-between gap-4"><div><h1 className="text-4xl font-black">AI Teacher Studio · V6</h1><p className="text-slate-600 mt-2">Một nơi để soạn KHBD, tạo câu hỏi, lập ma trận và kiểm định đề bằng AI có ngữ cảnh bài học.</p></div><a className="btn border" href="/admin/exam-builder">Mở trình tạo đề</a></div>
 <div className="grid lg:grid-cols-[240px_1fr] gap-6 mt-7"><aside className="card h-fit">{tabs.map(([id,label])=><button key={id} onClick={()=>{setTab(id);setAnswer('');setMsg('')}} className={`w-full text-left btn mb-2 ${tab===id?'bg-sky-900 text-white':'border'}`}>{label}</button>)}</aside>
 <section><div className="card"><div className="grid md:grid-cols-3 gap-3"><label>Lớp<select className="input" value={grade} onChange={e=>{setGrade(e.target.value);setLessonId('')}}>{grades.map(g=><option key={g}>{g}</option>)}</select></label><label className="md:col-span-2">Bài học<select className="input" value={lessonId} onChange={e=>setLessonId(e.target.value)}><option value="">-- Chưa chọn bài --</option>{filtered.map(l=><option key={l.id} value={l.id}>{l.chapter_code} · Bài {l.lesson_no}. {l.lesson_title}</option>)}</select></label></div>{tab==='question_set'&&<label className="block mt-4">Số câu<select className="input" value={count} onChange={e=>setCount(Number(e.target.value))}>{[1,3,5,10,15,20].map(n=><option key={n}>{n}</option>)}</select></label>}{(tab==='matrix'||tab==='exam_blueprint')&&<label className="block mt-4">Số câu dự kiến<input className="input" type="number" min={1} max={100} value={count} onChange={e=>setCount(Number(e.target.value))}/></label>}<textarea className="input min-h-40 mt-4" placeholder="Mô tả yêu cầu… Ví dụ: Bài Áp suất tác dụng lên bề mặt, tạo câu hỏi từ nhận biết đến vận dụng, có tình huống thực tế." value={request} onChange={e=>setRequest(e.target.value)}/><div className="flex flex-wrap gap-2 mt-4"><button className="btn bg-sky-900 text-white" disabled={busy||!request.trim()} onClick={run}>{busy?'AI đang xử lý…':'Thực hiện'}</button>{answer&&<button className="btn border" onClick={saveProject}>Lưu dự án</button>}{tab==='question_set'&&Array.isArray(answer)&&answer.length>0&&<button className="btn bg-emerald-700 text-white" onClick={saveQuestions}>Đưa vào ngân hàng câu hỏi</button>}</div></div>
 {msg&&<div className="card mt-4 text-red-700">{msg}</div>}{saved&&<div className="card mt-4 text-emerald-700">{saved}</div>}{answer&&<div className="card mt-5"><h2 className="text-xl font-black">Kết quả V6</h2>{Array.isArray(answer)?<div className="space-y-3 mt-4">{answer.map((q:any,i:number)=><article className="border rounded-xl p-4" key={i}><b>Câu {i+1} · {q.type}</b><p className="mt-2 whitespace-pre-wrap">{q.prompt}</p>{q.options&&<ol className="mt-2 list-[upper-alpha] ml-6">{(Array.isArray(q.options)?q.options:Object.values(q.options)).map((o:any,j:number)=><li key={j}>{String(o)}</li>)}</ol>}<p className="text-sm text-slate-500 mt-2">Đáp án: {Array.isArray(q.answer)?q.answer.map((x:any)=>x?'Đ':'S').join(' · '):String(q.answer??'')}</p></article>)}</div>:<pre className="mt-4 whitespace-pre-wrap overflow-auto">{typeof answer==='string'?answer:JSON.stringify(answer,null,2)}</pre>}</div>}</section></div></main>
}
