'use client';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
export default function Admin(){const [session,setSession]=useState<any>(null);const [rows,setRows]=useState<any[]>([]);const [msg,setMsg]=useState('');
 useEffect(()=>{supabase?.auth.getSession().then(({data})=>setSession(data.session));},[]);
 async function load(){if(!supabase)return;const {data,error}=await supabase.from('curriculum').select('*').order('grade').order('sort_order').limit(100);if(error)setMsg(error.message);else setRows(data||[])}
 async function signout(){await supabase?.auth.signOut();location.href='/login'}
 useEffect(()=>{if(session)load()},[session]);
 if(!session)return <main className="max-w-3xl mx-auto px-5 py-12"><div className="card"><h1 className="text-3xl font-black">Admin CMS</h1><p className="mt-3">Hãy đăng nhập bằng tài khoản quản trị.</p><a className="btn bg-sky-900 text-white inline-block mt-5" href="/login">Đăng nhập</a></div></main>;
 return <main className="max-w-7xl mx-auto px-5 py-10"><div className="flex justify-between gap-4 items-center"><div><h1 className="text-4xl font-black">Admin CMS v5</h1><p className="text-slate-600 mt-2">Quản trị dữ liệu KHTN SỐ</p></div><button onClick={signout} className="btn border">Đăng xuất</button></div><div className="grid md:grid-cols-4 gap-4 mt-8">{[['Cây chương trình','Quản lý chương/bài'],['Kho tài nguyên','URL, bản quyền, trạng thái'],['Ngân hàng câu hỏi','MCQ / Đúng-Sai / Ngắn / Tự luận'],['Người dùng','Học sinh / giáo viên / admin']].map(([a,b])=><div className="card" key={a}><h2 className="font-black">{a}</h2><p className="text-sm text-slate-600 mt-2">{b}</p></div>)}</div><div className="flex flex-wrap gap-2 mt-5"><a className="btn border" href="/admin/curriculum">Cây chương trình</a><a className="btn border" href="/admin/resources">Kho tài nguyên</a><a className="btn border" href="/admin/exams">Ngân hàng câu hỏi</a><a className="btn border" href="/admin/exam-builder">Tạo đề</a><a className="btn border" href="/admin/users">Người dùng</a></div><section className="card mt-8"><div className="flex justify-between"><h2 className="text-xl font-black">Cây chương trình hiện có</h2><button onClick={load} className="btn border">Tải lại</button></div>{msg&&<p className="text-red-600 mt-3">{msg}</p>}<div className="overflow-auto mt-4"><table className="w-full text-sm"><thead><tr><th className="text-left p-2">Lớp</th><th className="text-left p-2">Chương</th><th className="text-left p-2">Bài</th><th className="text-left p-2">Trạng thái</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-2">{r.grade}</td><td className="p-2">{r.chapter_code} – {r.chapter_title}</td><td className="p-2">{r.lesson_no}. {r.lesson_title}</td><td className="p-2">{r.status}</td></tr>)}</tbody></table></div></section></main>}
