'use client';
import {useEffect,useState} from 'react'; import Link from 'next/link'; import {supabase} from '@/lib/supabase';
export default function AIStudent(){
 const [profile,setProfile]=useState<any>(null),[attempts,setAttempts]=useState<any[]>([]),[report,setReport]=useState<any>(null),[set,setSet]=useState<any>(null),[plan,setPlan]=useState<any>(null),[mastery,setMastery]=useState<any[]>([]),[path,setPath]=useState<any>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function token(){const {data}=await supabase!.auth.getSession();if(!data.session){location.href='/login';return null}return data.session.access_token}
 async function load(){const t=await token();if(!t)return;const {data:{user}}=await supabase!.auth.getUser();if(!user)return;const [{data:p},{data:a},{data:pl}]=await Promise.all([supabase!.from('student_learning_profile').select('*').eq('user_id',user.id).maybeSingle(),supabase!.from('exam_attempts').select('id,exam_id,score,submitted_at,status').eq('user_id',user.id).eq('status','submitted').order('submitted_at',{ascending:false}).limit(8),supabase!.from('adaptive_learning_plans').select('*').eq('user_id',user.id).eq('status','active').order('generated_at',{ascending:false}).limit(1).maybeSingle()]);setProfile(p);setAttempts(a||[]);setPlan(pl)}
 useEffect(()=>{load()},[]);
 async function analyze(){setBusy(true);setMsg('');try{const t=await token();if(!t)return;const r=await fetch('/api/ai/student/analyze',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:'{}'});const j=await r.json();if(!r.ok)throw new Error(j.message||j.error||'Không phân tích được');setReport(j.report);setProfile({strengths:j.report.strengths,gaps:j.report.gaps,recommendations:j.report.next_steps})}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function adaptive(){setBusy(true);setMsg('');try{const t=await token();if(!t)return;const r=await fetch('/api/ai/student/adaptive',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:'{}'});const j=await r.json();if(!r.ok)throw new Error(j.message||j.error||'Không tạo được lộ trình');setPlan(j.plan);setMastery(j.mastery||[])}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function learningPath(){setBusy(true);setMsg('');try{const t=await token();if(!t)return;const r=await fetch('/api/ai/student/path',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:'{}'});const j=await r.json();if(!r.ok)throw new Error(j.message||j.error||'Không tạo được lộ trình học');setPath(j.path)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function completeStep(order:number){if(!path)return;try{const t=await token();if(!t)return;const r=await fetch('/api/ai/student/path/progress',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({path_id:path.id,order,completed:true})});const j=await r.json();if(r.ok)setPath(j.path)}catch(e:any){setMsg(e.message)}}
 async function practice(){setBusy(true);setMsg('');try{const t=await token();if(!t)return;const r=await fetch('/api/ai/student/practice',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({count:10})});const j=await r.json();if(!r.ok)throw new Error(j.message||j.error||'Không tạo được bài luyện');setSet(j.set)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 const gaps=report?.gaps||profile?.gaps||[];
 return <main className="max-w-7xl mx-auto px-5 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-sm font-bold text-sky-700">KHTN SỐ · V9</div><h1 className="text-4xl font-black">AI Student · Học tập thích ứng</h1><p className="text-slate-600 mt-2">Hệ thống học từ bài làm thật, kết nối học liệu và tự điều chỉnh lộ trình theo năng lực.</p></div><div className="flex flex-wrap gap-2"><button className="btn border" onClick={analyze} disabled={busy}>Phân tích bài làm</button><button className="btn bg-sky-900 text-white" onClick={adaptive} disabled={busy}>Tạo lộ trình 7 ngày</button><button className="btn border" onClick={practice} disabled={busy}>Tạo bài luyện</button><button className="btn border" onClick={learningPath} disabled={busy}>AI Learning Path</button></div></div>
 {msg&&<div className="card mt-5 text-red-700">{msg}</div>}
 <section className="grid md:grid-cols-4 gap-4 mt-6"><div className="card"><div className="text-sm text-slate-500">Bài đã nộp</div><div className="text-3xl font-black mt-1">{attempts.length}</div></div><div className="card"><div className="text-sm text-slate-500">Điểm gần nhất</div><div className="text-3xl font-black mt-1">{attempts[0]?.score ?? '—'}</div></div><div className="card"><div className="text-sm text-slate-500">Lỗ hổng</div><div className="text-3xl font-black mt-1">{gaps.length}</div></div><div className="card"><div className="text-sm text-slate-500">Lộ trình</div><div className="text-3xl font-black mt-1">{plan?'7 ngày':'—'}</div></div></section>
 {path&&<section className="card mt-5"><div className="flex justify-between items-center gap-4"><div><h2 className="text-xl font-black">AI Learning Path · Học theo đúng lỗ hổng</h2><p className="text-slate-500 mt-1">Mỗi bước nối bài học với học liệu và bài luyện phù hợp.</p></div><span className="badge">{path.status==='completed'?'Đã hoàn thành':'Đang học'}</span></div><div className="space-y-4 mt-5">{(path.items||[]).map((x:any)=><article key={x.order} className="border rounded-xl p-4"><div className="flex justify-between gap-3"><div><div className="text-xs font-bold text-sky-700">NGÀY {x.order}</div><h3 className="font-black">{x.lesson_title}</h3><p className="text-sm text-slate-600 mt-1">{x.goal||'Học và luyện tập'}</p>{x.why&&<p className="text-sm mt-2"><b>Vì sao:</b> {x.why}</p>}</div><button className="btn border h-fit" onClick={()=>completeStep(x.order)} disabled={x.completed}>{x.completed?'✓ Đã xong':'Hoàn thành'}</button></div>{x.resources?.length>0&&<div className="flex flex-wrap gap-2 mt-3">{x.resources.map((r:any)=><a key={r.id} href={r.url||'#'} target="_blank" rel="noreferrer" className="px-3 py-2 rounded-lg bg-sky-50 text-sky-800 text-sm font-semibold">{r.type}: {r.title} ↗</a>)}</div>}</article>)}</div></section>}
 {plan&&<section className="card mt-5"><div className="flex justify-between gap-4 items-center"><div><h2 className="text-xl font-black">Lộ trình học thích ứng 7 ngày</h2><p className="text-slate-500 mt-1">Dựa trên kết quả các bài thi gần đây.</p></div><span className="badge">{plan.summary?.weak||0} yếu · {plan.summary?.review||0} cần củng cố · {plan.summary?.mastered||0} đã vững</span></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-3 mt-5">{(plan.items||[]).map((x:any)=><article className="border rounded-xl p-4" key={x.order}><div className="text-xs font-bold text-sky-700">NGÀY {x.order}</div><h3 className="font-black mt-1">{x.lesson_title}</h3><p className="text-sm text-slate-600 mt-2">{x.goal}</p><div className="text-xs mt-3">Mức: <b>{x.difficulty}</b> · {x.estimated_minutes} phút</div></article>)}</div></section>}
 {mastery.length>0&&<section className="card mt-5"><h2 className="text-xl font-black">Bản đồ năng lực theo bài</h2><div className="space-y-3 mt-4">{mastery.slice(0,12).map((m:any)=><div key={m.lesson_id}><div className="flex justify-between text-sm"><b>{m.lesson_title}</b><span>{m.mastery}%</span></div><div className="h-3 bg-slate-100 rounded-full mt-1 overflow-hidden"><div className="h-full bg-sky-600" style={{width:`${m.mastery}%`}}/></div></div>)}</div></section>}
 <div className="grid lg:grid-cols-2 gap-5 mt-5"><section className="card"><h2 className="text-xl font-black">Điểm mạnh</h2>{(report?.strengths||profile?.strengths||[]).map((x:any,i:number)=><div key={i} className="mt-3 p-3 rounded-xl bg-emerald-50"><b>{x.lesson_title||'Kiến thức'}</b><div className="text-sm mt-1">{x.reason}</div></div>)}{!(report?.strengths||profile?.strengths||[]).length&&<p className="text-slate-500 mt-3">Hãy phân tích bài đã nộp để bắt đầu.</p>}</section><section className="card"><h2 className="text-xl font-black">Lỗ hổng cần củng cố</h2>{gaps.map((x:any,i:number)=><div key={i} className="mt-3 p-3 rounded-xl bg-amber-50"><div className="flex justify-between"><b>{x.lesson_title||'Kiến thức'}</b><span className="text-xs font-bold uppercase">{x.severity||'vừa'}</span></div><div className="text-sm mt-1">{x.evidence}</div><div className="text-sm mt-1"><b>Gợi ý:</b> {x.recommendation}</div></div>)}{!gaps.length&&<p className="text-slate-500 mt-3">Chưa phát hiện lỗ hổng.</p>}</section></div>
 {set&&<section className="card mt-5"><h2 className="text-xl font-black">{set.title}</h2><p className="text-slate-600 mt-1">{set.instructions}</p><Link className="btn bg-sky-900 text-white mt-4 inline-block" href={`/ai/student/practice/${set.id}`}>Làm bài luyện này</Link></section>}
 </main>
}
