'use client';
import {useEffect,useMemo,useState} from 'react';import {useRouter} from 'next/navigation';import {supabase} from '@/lib/supabase';import {shuffle} from '@/lib/exam';
export default function Exam({params}:{params:{id:string}}){const router=useRouter();const [exam,setExam]=useState<any>(null),[qs,setQs]=useState<any[]>([]),[answers,setAnswers]=useState<any>({}),[work,setWork]=useState<any>({}),[attempt,setAttempt]=useState<any>(null),[viol,setViol]=useState(0),[submitted,setSubmitted]=useState(false),[score,setScore]=useState<any>(null),[msg,setMsg]=useState(''),[seconds,setSeconds]=useState(0);
 useEffect(()=>{(async()=>{if(!supabase)return;const {data:e,error}=await supabase.from('exams').select('*').eq('id',params.id).single();if(error){setMsg(error.message);return}setExam(e);const {data:q,error:qe}=await supabase.rpc('get_exam_questions',{p_exam_id:params.id});if(qe){setMsg(qe.message);return}const ordered=e.shuffle_questions?shuffle(q||[]):q||[];setQs(ordered);const now=Date.now();if(e.open_at&&now<new Date(e.open_at).getTime()){setMsg('Đề chưa mở.');return}if(e.close_at&&now>new Date(e.close_at).getTime()){setMsg('Đã hết thời gian nhận bài.');return}const {data:{user}}=await supabase.auth.getUser();if(!user){router.push('/login');return}const {count}=await supabase.from('exam_attempts').select('id',{count:'exact',head:true}).eq('exam_id',params.id).eq('user_id',user.id);if((count||0)>=e.max_attempts){setMsg('Bạn đã hết số lần thi cho phép.');return}const {data:a}=await supabase.from('exam_attempts').insert({exam_id:params.id,user_id:user.id,question_order:ordered.map((x:any)=>x.id),started_at:new Date().toISOString(),status:'in_progress'}).select().single();if(a)setAttempt(a)})()},[params.id,router]);
 useEffect(()=>{if(submitted)return;const id=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(id)},[submitted]);
 useEffect(()=>{if(submitted)return;const on=()=>{if(document.hidden)setViol(v=>v+1)};document.addEventListener('visibilitychange',on);return()=>document.removeEventListener('visibilitychange',on)},[submitted]);
 useEffect(()=>{if(exam&&viol>=exam.tab_violation_limit&&!submitted)submit()},[viol,exam]);
 const answered=useMemo(()=>Object.keys(answers).length,[answers]);
 async function submit(){if(!supabase||submitted||!attempt)return;setSubmitted(true);const {data,error}=await supabase.rpc('submit_exam',{p_exam_id:params.id,p_attempt_id:attempt.id,p_answers:answers,p_work:work,p_violations:viol});if(error){setMsg(error.message);setSubmitted(false);return}setScore(data);}
 if(msg)return <main className="max-w-3xl mx-auto px-5 py-12"><div className="card text-red-700">{msg}</div></main>;
 if(!exam||!qs.length)return <main className="max-w-3xl mx-auto px-5 py-12"><div className="card">Đang tải đề thi…</div></main>;
 return <main className="max-w-5xl mx-auto px-5 py-8"><div className="card sticky top-2 z-10"><div className="flex flex-wrap justify-between gap-3"><div><b>{exam.title}</b><div className="text-sm text-slate-500">Đã trả lời {answered}/{qs.length} · vi phạm {viol}/{exam.tab_violation_limit}</div></div><div className="font-black">{Math.floor(seconds/60).toString().padStart(2,'0')}:{(seconds%60).toString().padStart(2,'0')}</div></div></div><div className="space-y-4 mt-5">{qs.map((q:any,i:number)=><section className="card" key={q.id}><h2 className="font-black">Câu {i+1} <span className="text-slate-400">({q.points} điểm)</span></h2><p className="mt-3 whitespace-pre-wrap">{q.prompt}</p>{q.type==='mcq'&&(Array.isArray(q.options)?q.options:Object.values(q.options||{})).map((o:any,j:number)=><label key={j} className="block border rounded-xl p-3 mt-3"><input type="radio" name={q.id} checked={answers[q.id]===String.fromCharCode(65+j)} onChange={()=>setAnswers((a:any)=>({...a,[q.id]:String.fromCharCode(65+j)}))}/> <b>{String.fromCharCode(65+j)}.</b> {String(o)}</label>)}{q.type==='tf'&&<div className="grid md:grid-cols-2 gap-3 mt-3">{[0,1,2,3].map(j=><label className="border rounded-xl p-3" key={j}>Ý {j+1}<select className="input" value={String((answers[q.id]||[])[j]??'')} onChange={e=>{const a=[...(answers[q.id]||['','','',''])];a[j]=e.target.value===''?'':e.target.value==='true';setAnswers((x:any)=>({...x,[q.id]:a}))}}><option value="">Chọn</option><option value="true">Đúng</option><option value="false">Sai</option></select></label>)}</div>}{q.type==='short'&&<input className="input" placeholder="Nhập đáp án" value={answers[q.id]||''} onChange={e=>setAnswers((a:any)=>({...a,[q.id]:e.target.value}))}/>} {q.type==='essay'&&<textarea className="input min-h-36" placeholder="Nhập bài làm…" value={answers[q.id]||''} onChange={e=>setAnswers((a:any)=>({...a,[q.id]:e.target.value}))}/>}</section>)}</div><div className="card mt-5 flex flex-wrap gap-3"><button disabled={submitted} onClick={submit} className="btn bg-sky-900 text-white disabled:opacity-50">{submitted?'Đã nộp bài':'Nộp bài'}</button>{submitted&&score&&<><span className="font-black self-center">Điểm khách quan: {score.score}/{score.max_score}</span><a className="btn border" href={`/exam/${score.attempt_id}/review`}>Xem Review</a></>}</div></main>}
